### ISSUE TITLE
Suite 4.7 GeoServer Advanced Workshop

### ISSUE THREAD

**Issue by jodygarnett** [boundlessgeo/workshops#25]
This workbook no longer functions directly against Suite 4.7 - this issue is used as a checklist as we prepare:

* [ ] data folder is cited in documentation, but is empty.

  ```
  BUILD FAILED
  adv/data does not exist.
  ```

* [ ] Rest API links are broken (for example http://docs.geoserver.org/stable/en/user/rest/api.html)

* [ ] Workbook assumes the default postgis database.
  This was formally setup with some sample data as part of Suite Install. Documentation indicates the following was expected.
  ```
  dem
  parks
  rails
  roads
  urban
  ```
  On the bright side the style files are still here.

* [ ]  be sure to recommend *firefox* for use of demo request builder (so displayed XML results can be read)

**Comment by bmmpxf** [comment]
Moving to different venue:

https://docs.google.com/document/d/1kDRz5tpK8oHSIr8rrwzZk0YfXg0EpVg2xlYWAHtlX0Q/edit
